namespace apPatcherApp
{
    using System;

    public enum ItemPropId : uint
    {
        kpidNoProperty = 0,
        kpidHandlerItemIndex = 2,
        kpidPath = 3,
        kpidName = 4,
        kpidExtension = 5,
        kpidIsFolder = 6,
        kpidSize = 7,
        kpidPackedSize = 8,
        kpidAttributes = 9,
        kpidCreationTime = 10,
        kpidLastAccessTime = 11,
        kpidLastWriteTime = 12,
        kpidSolid = 13,
        kpidCommented = 14,
        kpidEncrypted = 15,
        kpidSplitBefore = 0x10,
        kpidSplitAfter = 0x11,
        kpidDictionarySize = 0x12,
        kpidCRC = 0x13,
        kpidType = 20,
        kpidIsAnti = 0x15,
        kpidMethod = 0x16,
        kpidHostOS = 0x17,
        kpidFileSystem = 0x18,
        kpidUser = 0x19,
        kpidGroup = 0x1a,
        kpidBlock = 0x1b,
        kpidComment = 0x1c,
        kpidPosition = 0x1d,
        kpidPrefix = 30,
        kpidNumSubFolders = 0x1f,
        kpidNumSubFiles = 0x20,
        kpidUnpackVer = 0x21,
        kpidVolume = 0x22,
        kpidIsVolume = 0x23,
        kpidOffset = 0x24,
        kpidLinks = 0x25,
        kpidNumBlocks = 0x26,
        kpidNumVolumes = 0x27,
        kpidTimeType = 40,
        kpidBit64 = 0x29,
        kpidBigEndian = 0x2a,
        kpidCpu = 0x2b,
        kpidPhySize = 0x2c,
        kpidHeadersSize = 0x2d,
        kpidChecksum = 0x2e,
        kpidCharacts = 0x2f,
        kpidVa = 0x30,
        kpidTotalSize = 0x1100,
        kpidFreeSpace = 0x1101,
        kpidClusterSize = 0x1102,
        kpidVolumeName = 0x1103,
        kpidLocalName = 0x1200,
        kpidProvider = 0x1201,
        kpidUserDefined = 0x10000
    }
}

